overrides:
  ceph:
    conf:
      global:
        ms inject socket failures: 500
      osd:
        debug ms: 1
        debug osd: 20
        osd min pg log entries: 100
    fs: btrfs
    log-whitelist:
    - slow request
    path: /home/samuelj/ceph4
roles:
- - mon.a
  - osd.0
  - osd.1
  - osd.2
- - mds.a
  - osd.3
  - osd.4
  - osd.5
- - client.0
tasks:
- ceph:
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
- thrashosds:
    timeout: 1200
- rados:
    clients:
    - client.0
    objects: 500
    op_weights:
      delete: 50
      read: 100
      snap_create: 50
      snap_remove: 50
      snap_rollback: 50
      write: 100
    ops: 10000
