interactive-on-error: true
roles:
- - mon.0
  - osd.0
  - client.2
  - osd.1
  - osd.2
  - client.0
  - client.1
  - osd.3
#- - osd.4
#  - osd.5
#- - osd.6
#  - osd.7
#- - osd.4
#- - osd.5
overrides:
  ceph:
#    valgrind:
#       osd.0: [--tool=memcheck, --leak-check=full]
#       osd.1: [--tool=memcheck, --leak-check=full]
#       osd.2: [--tool=memcheck, --leak-check=full]
#       osd.3: [--tool=memcheck, --leak-check=full]
    fs: xfs
#    block_journal: true
    log-whitelist:
    - clocks not synchronized
#    path: /home/samuelj/ceph
    branch: next
    conf:
      osd:
        lockdep : false
        debug osd : 20
        debug ms : 1
        debug filestore : 20
        #debug journal : 20
        debug objecter : 20
        debug ms : 1
        debug client : 20
        journal aio : true
        filestore flusher : false
        filestore xattrs use omap : true
        filestore max inline xattr size : 0
        osd map dedup : false
        osd op threads : 10
        osd disk threads : 5
        osd recovery max active : 10
        osd recovery max chunk : 10485760
#kernel:
tasks:
- ceph: null
#- thrashosds:
#    chance_down: 0
#    min_in: 5
- radosbench:
     clients: [client.0]
     time: 36000
#- rados:
#    clients:
#    - client.0
###    - client.1
#    - client.2
#    objects: 5000
#    size: 1000
#    op_weights:
#      write: 100
#      delete: 50
#      read: 100
#      snap_create: 30
#      rollback: 30
#      snap_remove: 35
#      setattr: 100
#      rmattr: 50
#      watch: 10
#    ops: 30000
