overrides:
  admin_socket:
    branch: wip-sam-testing
  ceph:
    conf:
#      global:
#        ms inject socket failures: 5000
      mon:
        debug mon: 20
        debug ms: 1
        debug paxos: 20
      osd:
#        debug filestore: 20
#        debug journal: 20
        debug ms: 1
#        debug osd: 20
        osd max pg log entries: 14
        osd min pg log entries: 10
    fs: xfs
    log-whitelist:
    - slow request
    - must scrub before tier agent can activate
    sha1: 4c4f35e9099313ca5f86dec4f1ea045513d9648b
    dump_pglogs: true
  ceph-deploy:
    branch:
      dev: wip-sam-testing
    conf:
      client:
        log file: /var/log/ceph/ceph-$name.$pid.log
      mon:
        debug mon: 1
        debug ms: 20
        debug paxos: 20
        osd default pool size: 2
  install:
    ceph:
      branch: wip-sam-testing
  s3tests:
    branch: master
  workunit:
    branch: wip-sam-testing
roles:
- - mon.a
  - osd.0
  - osd.1
  - osd.2
  - osd.3
  - client.0
- - mon.b
  - osd.4
  - osd.5
  - osd.6
  - osd.7
  - client.1
- - osd.8
  - mon.c
  - osd.9
  - osd.10
  - osd.11
tasks:
#- chef: null
#- clock.check: null
- install: null
- ceph:
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
- exec:
    client.0:
      - ceph osd pool create foo 1200
      - ceph osd pool set foo size 3
      - ceph osd pool set foo min_size 2
#- watch_notify_same_primary:
#    clients: [client.0]
- interactive:

verbose: false
