interactive-on-error: true
roles:
- [mon.a, osd.0, osd.1, mon.b, mon.c, osd.2, osd.3, client.0]
overrides:
  ceph:
    conf:
      global:
        ms inject delay max: 1
        ms inject delay probability: 0.005
        ms inject delay type: osd
        ms inject internal delays: 0.002
        ms inject socket failures: 2500
tasks:
- install.ship_utilities: null
- install:
    branch: firefly
- ceph:
    branch: firefly
    fs: btrfs
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
- thrashosds:
    chance_pgnum_grow: 2
    chance_pgpnum_fix: 1
    timeout: 1200
- radosbench:
    clients:
    - client.0
    time: 1800
