overrides:
  admin_socket:
    branch: wip-sam-working
  ceph:
    conf:
      mon:
        debug mon: 20
        debug ms: 1
        debug paxos: 20
      osd:
        debug filestore: 20
        debug journal: 20
        debug ms: 1
        debug osd: 20
        osd op thread timeout: 60
        osd sloppy crc: true
    fs: xfs
    log-whitelist:
    - slow request
    branch: wip-sam-working
  ceph-deploy:
    branch:
      dev: wip-sam-working
    conf:
      client:
        log file: /var/log/ceph/ceph-$name.$pid.log
      mon:
        debug mon: 1
        debug ms: 20
        debug paxos: 20
        osd default pool size: 2
  install:
    ceph:
      branch: wip-sam-working
  s3tests:
    branch: master
  workunit:
    branch: wip-sam-working
roles:
- - mon.a
  - mds.a
  - osd.0
  - osd.1
- - mon.b
  - mds.a-s
  - mon.c
  - osd.2
  - osd.3
- - client.0
tasks:
- chef: null
- clock.check: null
- install: null
- ceph:
    fs: xfs
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
- thrashosds:
    chance_pgnum_grow: 2
    chance_pgpnum_fix: 1
    timeout: 1200
- exec:
    client.0:
    - ceph osd pool create base 4
    - ceph osd pool create cache 4
    - ceph osd tier add base cache
    - ceph osd tier cache-mode cache writeback
    - ceph osd tier set-overlay base cache
    - ceph osd pool set cache hit_set_type bloom
    - ceph osd pool set cache hit_set_count 8
    - ceph osd pool set cache hit_set_period 3600
    - ceph osd pool set cache target_max_objects 250
- rados:
    clients:
    - client.0
    objects: 500
    op_weights:
      copy_from: 50
      delete: 50
      evict: 50
      flush: 50
      read: 100
      rollback: 50
      snap_create: 50
      snap_remove: 50
      try_flush: 50
      write: 100
    ops: 4000
    pool_snaps: true
    pools:
    - base
